include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    omit_local_variable_types: false
    sort_pub_dependencies: false
    flutter_style_todos: false