name: spacefood_express
description: "A new Flutter project."
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.3
  google_fonts: 6.1.0

  #local packages
  flutter_layer: 1.0.0
  flame_layer: 1.0.0
  shared: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true