name: flame_layer
description: "Game core and UI based on Flame Engine"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flame: 1.12.0
  flame_bloc: 1.10.7
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  flame_tiled: 1.18.1
  flame_audio: 2.1.5
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/food/
    - assets/tiles/
    - assets/audio/